README.md, build.gradle, settings.gradle, src/main/java/uk/nhs/hee/tis/trainee/config/SentryConfiguration.java, src/main/java/uk/nhs/hee/tis/trainee/sync/TisTraineeSyncApplication.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/sync/TisTraineeSyncApplicationTest.java
The template this project was created from contains several TODOs that
need following to create the service correctly. Follow and remove the
TODOs.
TISNEW-4304
=> refactor: Follow TODOs to convert from template

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/api/RecordResource.java, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/RecordDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Record.java, src/test/java/uk/nhs/hee/tis/trainee/sync/api/RecordResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/api/TestUtil.java
No more logic is needed this sprint, just created a api to make sure the record sent by aws lambda is received by this service.
TISNEW-4306
=> feat: add a RecordResource to log the received record from tis stage

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Record.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java
Data load operations were not handled and are needed to support the
initial full load.
TISNEW-4307
=> fix: Handle data load operations

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
When the TIS PersonalDetails table changes, the dateOfBirth and gender fields are sent to update trainee personal information.
TISNEW-5154: Sync Personal Details
=> feat: send patch for gender and date of birth updates

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
=> feat: Add sync for GDC, GMC and Owner details

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
Sync the public health number from the Person table. The trainee-details
POST endpoint for creating a skeleton has been removed in favour of
using the patch endpoint for both update and profile creation.
TISNEW-5238
=> feat: Sync public health number

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
Synchronize updates to the Qualification table to the trainee details
service via patch request.
TISNEW-5238
=> feat: Synchronize qualifications to trainee details

src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
TIS21-1032
Added placement fields and relative mappers
=> feat: add placement

src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
=> feat: add Programme Membership Mapping

src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/RecordUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Operation.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Record.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/RecordServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncServiceTest.java
=> refactor: Created Operation enumeration

src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java
=> refactor: Only sync when enrich was successful

src/main/java/uk/nhs/hee/tis/trainee/sync/model/Person.java, src/main/java/uk/nhs/hee/tis/trainee/sync/repository/PersonRepository.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PersonService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PersonServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
TIS21-1032 
refactor: created PersonRepository interface, a Person model and PersonService classes.
test: personServiceTest tests have been created for PersonService
=> Create person model and person repository

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Person.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Placement.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Post.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Site.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Trust.java
The scope should be `prototype` and not `Prototype`
TIS21-1032
=> fix: Resolve issue with person sync

.github/workflows/ci-cd-workflow.yml
=> fix: explicitly push all image tags

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncServiceTest.java
=> feat: Add wholeTimeEquivalent to the placement dto

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json
can be increase further if not enough
=> chore: increase cpu

src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
=> Fix: use REST delete instead of patch

src/main/resources/application.yml
Enabling debug logging will allow tracking what resources are being
requested from TIS.
TIS21-1034
=> chore: Enable debug logging for sync services

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementEventListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PersonCachingTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
=> Feat: delete placements

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java
=> feat: Add handling for DBC syncing

Dockerfile
=> chore: Give the image more memory

src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacade.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java
=> Feat: add curriculum end date

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/Status.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/ReferenceMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/ReferenceUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/ReferenceMapperTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java
Add `placementGrade`, `trainingGrade` fields for the Grade reference
type, also add the common `Status` field.
TIS21-1399
=> feat: Add additional grade fields

README.md
fix: title
Also fixing MD formatting
TIS21-1343: Ensure team have permissions to re-run syncs
=> chore: add support section to README

README.md
Github isn't as forgiving as the local editor
NO-TICKET
=> chore: fix MD formatting

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json, build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementListener.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementListenerTest.java
Create a PlacementListener to retrieve messages from the queue and call
the placement service.
Update task definitions to provide the `PLACEMENT_QUEUE_URL` env var.
TIS21-1684
=> feat: Read from and process placement queue

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncServiceTest.java
When a placement is received from the record queue it should be added to
the placement queue to be processed by the placement queue listener.
TIS21-1684
=> feat: Add incoming placements to placement queue

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json
=> chore: Add missing POST_QUEUE_URL env var to deploy

.github/workflows/ci-cd-workflow.yml, .github/workflows/pr-analysis.yml
=> chore: Rename master to main

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
Call the qualification delete endpoint in trainee details when a sync
message shows that the qualification was deleted.
TIS21-2549
=> feat: handle qualification deletion

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeEventListener.java
Do not cascade to affect programme membership records.
TIS21-2613
=> feat: handle programme deletions

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json, build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProfileCreatedEvent.java, src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProfileCreatedEventListener.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProfileCreatedEventListenerTest.java
When a profile create event is received all associated data should be
requested.
TIS21-3001
TIS21-3105
=> feat: add listener for ProfileCreateEvents

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json
=> chore: add Redis username and password in task-definition

.aws/task-definition-pre-prod.json, src/main/resources/application.yml
=> fix: enable SSL connection for redis

src/main/java/uk/nhs/hee/tis/trainee/sync/config/RedisConfig.java
=> fix: add SSL config to redis client builder

src/main/java/uk/nhs/hee/tis/trainee/sync/config/RedisConfig.java
=> fix: remove starttls

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json
=> chore: update redis param for Prod

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/event/GradeEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Grade.java, src/main/java/uk/nhs/hee/tis/trainee/sync/repository/GradeRepository.java, src/main/java/uk/nhs/hee/tis/trainee/sync/repository/PlacementRepository.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/GradeSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/event/GradeEventListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/GradeSyncServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncServiceTest.java
- Create `grade` table in Sync
- Enrich trainee placement grade abbreviation according to the grade table
- Trigger placement re-enrichment after grade is updated
TIS21-3123
=> Grade abbreviation syncing

src/main/resources/application.yml
hopefully this will send all read requests to the non primary instances and send writes to the master therefore making the infrastructure work more efficiently for us
=> add replica set info to uri

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/config/WebConfig.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/CurriculumMembershipSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/CurriculumSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/DataRequestService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/GradeSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PersonService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSpecialtySyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeMembershipSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/RecordService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/RequestCacheService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/SiteSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/SpecialtySyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncService.java
instrumentation and configuration for use by the XRay daemon hosted on aws
TIS21-1970
=> X ray instrumentation

.aws/task-definition-template.json, build.gradle, src/main/resources/application.yml
=> fix: set AWS XRay daemon host address

.aws/task-definition-template.json, src/main/java/uk/nhs/hee/tis/trainee/sync/config/EventNotificationProperties.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
TODO: filter by field updates that actually affect credentials.
TIS21-4150
=> feat: update events for credential SNS

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
As per https://github.com/Health-Education-England/tis-trainee-credentials/pull/51
TIS21-4147
TIS21-4347
=> fix: omit timestamps from event messages

.aws/task-definition-template.json, build.gradle
=> fix: task definition param reference

src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapper.java, src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapperTest.java
=> fix: get tisId from id or uuid field

.aws/task-definition-template.json, build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/config/EventNotificationProperties.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
Publish events to appropriate SNS topics when receiving an update for any table affecting the personal details data.
- ContactDetails
- GdcDetails
- GmcDetails
- Person
- PersonOwner
- PersonalDetails
TIS21-4085
TIS21-4076
=> feat: publish events when updating personal details

build.gradle, src/main/resources/application.yml
The application property name for the UpdatePerson SNS topic is incorrect, as a result the topic is not published to for person updates.
TIS21-4085
TIS21-4076
=> fix: person topic app property name

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java
Dependent on 
https://github.com/Health-Education-England/tis-trainee-reference/pull/262 
and
https://github.com/Health-Education-England/TIS-OPS/pull/653
TIS21-4903
=> fix: add ProgrammeMembershipType handling

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/AggregateCurriculumMembershipDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacade.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapper.java, src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnrichmentIntegrationTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapperTest.java
=> feat: curriculum specialty

.aws/task-definition-template.json, build.gradle.kts
=> chore: change to use FIFO update placement SNS topic

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java, src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java
=> feat: enrich Post Owner (local office) into Placement

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/ReferenceMapper.java, src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/ReferenceMapperTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java
To resolve the missing tisId field, and the status for LocalOfficeContactTypes.
TIS21-5698
=> fix: LocalOfficeContact and Type mapper

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java
=> fix: include record in delete event messages

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/AggregateProgrammeMembershipDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapper.java, src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapperTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/FifoMessagingServiceTest.java
=> feat: add TrainingPathway to aggregate PM

.aws/task-definition-template.json, build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/sync/config/MongoConfiguration.java, src/main/java/uk/nhs/hee/tis/trainee/sync/event/DbcEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java, src/main/java/uk/nhs/hee/tis/trainee/sync/model/Dbc.java, src/main/java/uk/nhs/hee/tis/trainee/sync/repository/DbcRepository.java, src/main/java/uk/nhs/hee/tis/trainee/sync/repository/ProgrammeRepository.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/DbcSyncService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/sync/config/MongoConfigurationTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/event/DbcEventListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/DbcSyncServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeSyncServiceTest.java
This will be needed to link UserDesignatedBody to programmes, and to cascade changes affecting RO's. Its a chunky PR (though pretty standard stuff).
Dependent on: https://github.com/Health-Education-England/TIS-OPS/pull/815
TIS21-5825
=> feat: include DBC in sync db

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/sync/dto/AggregateProgrammeMembershipDto.java, src/main/java/uk/nhs/hee/tis/trainee/sync/event/LocalOfficeEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeListener.java, src/main/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacade.java, src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapper.java, src/main/java/uk/nhs/hee/tis/trainee/sync/repository/LocalOfficeRepository.java, src/main/java/uk/nhs/hee/tis/trainee/sync/service/LocalOfficeSyncService.java, src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapperTest.java, src/test/java/uk/nhs/hee/tis/trainee/sync/service/LocalOfficeSyncServiceTest.java
Note that requesting LocalOffice by name from the tis-sync service still needs to be implemented (it is likely to be a rare request - and if the LO record arrives thereafter it will trigger a refresh of related programmes and programme memberships in any event)
TIS21-6274
=> feat: PM designated body
