build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/ReferenceUtil.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapperTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java

Some reference types such as College and LocalOffice use a `name` field
instead of `label`. If label is not populated then fall back to the name
field's value.
TISNEW-4307

fix: Handle references with name instead of label

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

A trainee not being found in the trainee details service is a valid
use case, in such scenarios we simply do not process the record.
Currently when a 404 is returned an exception is throw, which breaks the
kinesis stream updates. Catch 404s and simply log the error so that sync
can continue.
TISNEW-5344

fix: Don't throw exception when trainee not found

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

When the Person table is being updated a skeleton profile should be
created if one does not already exist. This allows other
synchronizations, which depend on a trainee having a TISSS record, to
find the profile to add further details to.
TISNEW-3833

feat: Synchronize initial skeleton trainee profile

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Trust.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/PlacementRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/PostRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/TrustRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncServiceTest.java

To fully populate the placement record it must be possible to get all of the associated Placement, Post and Trust from either of the record types.
Add service and repository methods to facilitate those lookups.

Feature/add services for Placement <-> Post <-> Trust

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java

Some posts do not having employing or training bodies and will return a
null ID for these fields. Currently the placement enricher attempts to
still get the trust names and causes a NPE.
TIS21-1032

fix: Handle Posts without employing/training bodies

---

.aws/task-definition-pre-prod.json

A connection to SQS requires AWS credentials to be provided, add the
missing task role so these can be provided automatically during deploy.
TIS21-1032

chore: Provide runtime credentials in pre-prod

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/SiteSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/SiteSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncServiceTest.java

Requests are sent for every object not found, regardless of whether it
has already been requested. Keep track of the IDs that have been
requested and skip the request if it is already pending.
When a record is received for syncing remove it from the requested ID
list if found.
TIS21-1032

fix: Do not send duplicate request for data

---

src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/SiteSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TrustSyncService.java

To make consistent with PostSyncService and other usage

chore: Refactor syncService entity name references

---

src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

As we filter based on role locally, there is no need to do this by catching HTTP 404s
refactor: use the trainee id from the converted DTO
The trainee ID might be in the "id" field or it might be somewhere else
i.e. For Qualification, it is actually in the "personId" field.
TIS21-1032: Synchronise placement details

feat: throw any Exceptions from trainee details

---

.aws/task-definition-pre-prod.json
.aws/task-definition-prod.json
build.gradle
src/main/resources/application.yml

Update application.yml to remove the default queue name to avoid
accidentally processing and removing entries when running the
application locally.
TIS21-1032

chore: Set queue URL in task definitions per env

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/config/MongoConfiguration.java

The generated name for the programme membership compound index is too
long, provide a concise name that meets the restrictions.
TIS21-66

fix: Compound prog membership index name too long

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/CurriculumEventListener.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/CurriculumEventListenerTest.java

The EventListener is invoked before the Caching proxy sees the successful save.
This leads to a stale cache value being used.
TIS21-66: Sync and display ProgrammeMemberships

feat: update the cache before calling the enricher

---

src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListener.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListenerTest.java

Its a harmless error, but it looks ugly in the logs, e.g.:
2021-04-07 10:24:42.976  INFO 1 --- [io-8208-exec-10] u.n.h.t.trainee.sync.api.RecordResource  : REST request to process Record : RecordDto(data={id=284052, programmeMembershipType=SUBSTANTIVE, curriculumStartDate=2017-08-02, curriculumEndDate=2019-08-06, programmeStartDate=2017-08-02, programmeEndDate=2019-08-06, programmeId=761, curriculumId=487, trainingNumberId=1817, personId=120165, amendedDate=2021-03-10T15:14:54.895Z, trainingPathway=N/A}, metadata={timestamp=2021-03-31T11:03:51.122045Z, record-type=data, operation=delete, partition-key-type=schema-table, schema-name=tcs, table-name=ProgrammeMembership, transaction-id=11480454387235})
2021-04-07 10:24:42.976  INFO 1 --- [io-8208-exec-10] u.n.h.t.t.sync.service.RecordService …

fix: avoid NPE on delete of non-existent PM

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/Status.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/ReferenceSyncServiceTest.java

Curriculum sync is failing as some records have "DELETE" as the status,
which is not accounted for.
TIS21-1451

fix: Add DELETE status

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

Some trainees have the role `Dr in Training` instead of `DR in
Training`, these profiles are not properly synced. Ignore the casing
when comparing the role to ensure we catch edge cases.
TIS21-1624

fix: Handle incorrect required role casing

---

.aws/task-definition-pre-prod.json

Update the preprod log group name to meet the current conventions.
TIS21-1665

chore: Update preprod log group name

---

.github/workflows/ci-cd-workflow.yml

The service name was changed from `trainee-sync` to `tis-trainee-sync`.
TIS-1665

chore: Fix service name in preprod deployment

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/RecordUtil.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Operation.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Record.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/RecordType.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/RecordService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/RecordServiceTest.java

Some DMS records are sent with a record type of `control`, these records
notify of important events in the stream such as creating a table.
Control records contain no `data` so the record data map must be allowed
to be null.
Nothing needs to be done when receiving a control record, so processing
should be skipped but it should not cause an exception.
TIS21-1919

fix: Handle non-data DMS records

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PostListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncService.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PostListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PostSyncServiceTest.java

Add a queue for post records, a listener should read from the post queue
and perform the post sync for each record.
When a post is received on the record queue, the post should be
re-queued in the post queue.
TIS21-1691

feat: Add Post record queue

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/ReferenceDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/ReferenceMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/ReferenceUtil.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/ReferenceMapperTest.java

The DBC has had `type` and `internal` fields added to allow better
identification of the scope/context of each DBC.
TIS21-1659

feat: Add type and internal fields to DBC

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/ReferenceUtil.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/ReferenceMapperTest.java

Boolean values were expected to be `"true"` and `"false"` but are
actually `"1"` and `"0"` respectively.
Update ReferenceUtil to correctly map the boolean values.
TIS21-1659

fix: Boolean values not handled correctly

---

.aws/task-definition-pre-prod.json
.aws/task-definition-prod.json
build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PostListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSpecialtySyncService.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PostListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSpecialtySyncServiceTest.java

Rather than trigger enrichment when a PlacementSpecialty is recieved, it
should queue or request the associated placement (depending if it
exists).
When a PlacementSpecialty is received on the record queue, requeue it on
the PlacementSpecialty queue.
TIS21-1693

feat: Process PlacementSpecialty via queue

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java

When a specialty is updated the enricher gets all related placement
specialties and attempts to process them together, due to the amount of
time it can take to process large specialties this approach can cause
issues.
Placement specialties related to the updated specialty should instead be
queued up in the placement specialty queue, which in turn will handle
the associated placements.
TIS21-1692

feat: Expand Specialty to PlacementSpecialty queue

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

Handle the deletion of TIS data that feeds the `traineeProfile` object,
this can be achieved by patching with a blank DTO to purge the
associated data.
TIS21-2549

feat: handle deletion of personalDetails data

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PostEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/SiteEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/TrustEventListener.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/TrustEventListenerTest.java

When a `DELETE` message is received for Specialty or Trust, the
associated PlacementSpecialtys or Posts should also be deleted from the
sync lookup tables.
Remove `onAfterDelete` methods from Post and Site event listeners, they
are directly associated with placements and deleting the placement would
force deletion from the trainee profile. Removing a placement from the
trainee profile should only be done when the placement itself is
deleted.
TIS21-2549

feat: purge data associated with deleted records

---

src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java

When a placement specialty is deleted additional checks are made on
whether the associated placement is already deleted, or whether the
placement already has a new specialty link.
If these are not true then the placement is re-enriched, requesting any
missing data as part of the process.
While there is no guarantee of order received, there is an expectation
that the sync service would eventually get any missing messages, either
the placement deletion or the new placement specialty.
The existing re-enrichment functionality on delete should be removed for
consistency with other related data, which are currently just deleted
without any affect on the placement - deletion nor enrichment.
Any handling of similar scenarios should consider all data deletions
that may affect a placement and …

feat: remove enrichment on placementspecialty delete

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyEventListener.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyEventListenerTest.java

When handling PlacementSpecialty events the listener requests the
associated Placement if it is not found in the lookup data.
When doing a full load on an empty database this causes a large number
of requests, as no matter which order Placement and PlacementSpecialty
are loaded the other can not yet exist and will always be requested.
Removing the request from the PlacementSpecialty event listener allows
the PlacementSpecialty lookup data to be loaded prior to the Placements.
In the standard use case of a PlacementSpecialty being created, it is
fair to expect that the Placement will already exist in the lookup data,
or else the Placement insert message would be received eventually.
The Placement should still have the ability to request
PlacementSpecialty records should none exist in the …

fix: no Placement request for PlacementSpecialty

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/CurriculumEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/CurriculumMembershipEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/CurriculumMembershipEnricherFacade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/CurriculumMembership.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/CurriculumMembershipRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/CurriculumMembershipSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/RecordService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingCurriculumMembershipIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/CurriculumEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/CurriculumMembershipEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/CurriculumMembershipEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/CurriculumMembershipSyncServiceTest.java

Start using the new CurriculumMembership table events queue, but still populate a ProgrammeMembershipDTO and the same 'programmeMemberships' array in TraineeProfile MongoDB.
Note that ProgrammeMembership sync is turned-off by this PR, but the work to refactor and re-enable this with the new ProgrammeMembership table design will only be done once the revised table is finalised.
Needs https://github.com/Health-Education-England/TIS-OPS/pull/420 to be merged to be 'activated'
TIS21-2509

Feat: ProgrammeMembership to CurriculumMembership

---

src/main/java/uk/nhs/hee/tis/trainee/sync/migration/CopyProgrammeMembershipToCurriculumMembership.java

Staging mongo is v3.6.0 which fails to create the compound index with its default name, throwing a 'namespace name generated from index name is too long' exception, since the default name is more than 127 bytes
('data.programmeId_1_data.curriculumId_1_data.personId_1_data.programmeMembershipType_1_data.programmeStartDate_1_data.programmeEndDate_1' is 135 characters).
This should fix this. Since the other indexes are all prefixed 'data.' the name(s) for the compound index(es) should never collide with these.
TIS21-2509

Fix: compound index creation

---

src/main/resources/application.yml

The sync service occasionally requests placement specialty for
placements with invalid IDs, enable event debug logging to give more
insight in to the incoming data to identify when/where the invalid ID
enters the sync service.
TIS21-SHED

chore: enabled event debug logging

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

Trainees with role Placeholder or Dummy Record should not have
TraineeProfiles created.
TIS21-3170: Do not create profiles for placeholder trainees

fix: do not create profiles for placeholder record

---

src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java

The purpose of this is to confirm or refute a possible cause for the bug
below, since there is no DocumentDB query logging.
Based on observed instances of the bug, data is sometimes logged as arriving in
tis-trainee-sync but there is no matching log entry in
tis-trainee-details to show it being processed, nor an exception from
the tis-trainee-details API call. As such, the most likely scenario is
that there is an intermittent failure with the findById(), either at a
database or cache level.
TIS21-3195: Single-trainee data refresh missing data

fix: add logging for trainee not found

---

.github/workflows/ci-cd-workflow.yml

update actions/setup-java to 3.6.0
attempt to fix the warning: `The set-output command is deprecated and will be disabled soon`
Update this repo as a test. Will make sure Dependapot is covering version update in all other repos in the future.
Reference:
https://github.com/actions/setup-java/issues/393
https://github.com/GetStream/stream-chat-android/issues/4279

fix: update actions/setup-java in cicd-workflow

---

.aws/task-definition-template.json

Update the task definition template to use
`/tis/trainee/sync/${environment}/queue-url/delete-placement` instead of `/tis/trainee/sync/${environment}/queue-url/delete-placement-event` and `/tis/trainee/sync/${environment}/queue-url/delete-programme-membership` instead of
`/tis/trainee/sync/${environment}/queue-url/delete-programme-membership-event`.
TIS21-4128
TIS21-4301

chore: use correct queue param names

---

.aws/task-definition-template.json

The current params point to SQS queues but should point to topic ARNs, the missing parameters have now been added. Update the task definition template to point to the new params.
TIS21-4128
TIS21-4301

fix: use new SNS params instead of SQS queues

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSpecialtyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/PlacementSpecialty.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Specialty.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/PlacementSpecialtyRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/SpecialtyRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/CurriculumSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/SpecialtySyncService.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingSpecialtyIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/RequestCacheServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/SpecialtySyncServiceTest.java

Sentry is still using `SENTRY_ENVIRONMENT` but that variable was removed from the task definition, use the `ENVIRONMENT` variable via `application.environment` instead.
Add missing copyright notices for Specialty classes.
TIS21-4230
TIS21-4224

fix: sentry config

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/config/EcsMetadataConfiguration.java
src/main/java/uk/nhs/hee/tis/trainee/sync/config/RedisConfig.java
src/main/java/uk/nhs/hee/tis/trainee/sync/config/SentryConfiguration.java
src/test/java/uk/nhs/hee/tis/trainee/sync/config/EcsMetadataConfigurationTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/config/SentryConfigurationTest.java

The ECS metadata endpoint provides information about what and where an instance of this service is running. Including that information on Sentry error captures allows easy identification of where an issue is occuring.
Update the Sentry configurations to include the ECS metadata. When not running in an ECS environment (i.e. the metadata endpoint is not provided) the Sentry reports should not include extra metadata e.g. showing null values.
TIS21-4443
TIS21-4379

feat: log ECS metadata with X-Ray and Sentry

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/config/MongoConfiguration.java
src/main/java/uk/nhs/hee/tis/trainee/sync/config/RedisConfig.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/ProgrammeMembershipMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/ProgrammeMembership.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/ProgrammeMembershipRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeMembershipSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/RecordService.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingProgrammeMembershipIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/config/MongoConfigurationTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/ProgrammeMembershipMapperTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeMembershipSyncServiceTest.java

Refactor the ProgrammeMembership entity to be a proper concrete POJO instead of an empty extension of the `Record` POJO. Create a mapper to convert between the Record's data map the the new POJO.
Refactor the repository, service, event listeners and enricher for ProgrammeMembership to use the new POJO. The enricher in particular needs a lot of work and will be completed in later commits, the tests should be disabled to avoid any temporary failures.
Update RecordService to remove the skipping of PM data and instead remove the enricher calls from the PM event listener. This allows the new PM POJO to be saved in the cache and database without triggering an enrichment.
TIS21-4170
TIS21-2399

refactor: ProgrammeMembership entity

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListener.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListenerTest.java

Example error logs for programme membership deletions:
2023-06-07 07:29:35.889 ERROR 1 --- [nerContainer-37]
i.a.c.m.listener.QueueMessageHandler     : An exception occurred while
invoking the handler method
java.lang.ClassCastException: class java.util.UUID cannot be cast to
class java.lang.String (java.util.UUID and java.lang.String are in
module java.base of loader 'bootstrap')
at org.bson.Document.getString(Document.java:306)
~[bson-4.6.1.jar:na]
at
uk.nhs.hee.tis.trainee.sync.event.ProgrammeMembershipEventListener.onBeforeDelete(ProgrammeMembershipEventListener.java:75)
~[classes/:na]
NO-TICKET

fix: programme membership uuid key

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeMembershipSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingProgrammeMembershipIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeMembershipSyncServiceTest.java

The programme membership sync queue is populated by Programme and CurriculumMembership services, but the SQS listener is missing. Create the SQS listener to read from the PM queue and perform deletions/enrichment.
A slight divergence to the typical pattern is needed, as we can no longer check if the Record is an instance of ProgrammeMembership. Check the record's table instead.
TIS21-2399
TIS21-4172

fix: add missing PM queue listener

---

src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipListenerTest.java

The programme membership listener tests create an instance of Placement instead of Record. This doesn't break the test but isn't a correct reflection of the expectation.
TIS21-2399

test: create record instead of placement

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapper.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapperTest.java

When performing a record mapping, the `tisId` field is being overwritten if a UUID exists in the data.
The UUID should only be populated in to the `tisId` field if no other value is available (i.e. `tisId` is `null`).
TIS21-2399

fix: record uuid should not overwrite TIS ID.

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

When pubishing to a FIFO SNS topic the Message Group ID must be set, this defines which groups of messages must be procesed in order. Create an ID for FIFO publishing which uses the schema, table and record ID to ensure that all messages for the same data record are processed in order. Taking this approach rather than having every message be in the same group ensure that we can be efficient and not block updates that can be handled in parallel.
TIS21-4085
TIS21-4076

fix: set message group ID for SNS publish

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

Personal details updates are now handled by messaging and the API endpoints are to be removed. Disable to the calls to those API endpoints.
`Person`/`basic-details` being emitted as an event has been rolled back due to additional behaviour that needs to be account for, specifically the deletion of the trainee profile.
TIS21-4085
TIS21-4076

feat: disable personal details update API calls

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSiteEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/SiteEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/PlacementSiteRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSiteSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/PlacementSiteEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/SiteEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSiteSyncServiceTest.java

Placements should be expanded in to the queue, or requested when missing based on PlacementSite relationships.
Create an event listener for placement sites which will expand placements found using the related placementId, or alternatively request the missing placement when not found. A deleted PlacementSite should also trigger a re-sync of the Placement by re-queuing it to be synced.
Update the site event listener to also handle the placements related to "other sites", using the PlacementSite records as a joining record.
TIS21-4969
TIS21-4396

feat: placement request/expansion for other sites

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapperTest.java

The WTE field naming differs based on how it was received. If received via DMS it has the database naming of
`placementWholeTimeEquivalent`. However, if it is sent as a result of a re-sync request it is named `wholeTimeEquivalent`.
Update the TraineeDetailsMapper to handle both names for this field.
TIS21-5140

fix: WTE field naming variations

---

.aws/task-definition-template.json
build.gradle

Dependent on https://github.com/Health-Education-England/TIS-OPS/pull/680
TIS21-5057

fix: use new FIFO SNS for PM updates

---

build.gradle
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

A wrapped Record object was being sent, which the notification service was not expecting. This was consistent with the data structures sent to tis-trainee-details and tis-trainee-credentials, but longer term the intention is to refactor these as well.
NO-TICKET

fix: send unwrapped PmEventDto for CoJ SNS broadcast

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/AggregateCurriculumMembershipDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapper.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnrichmentIntegrationTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapperTest.java

This is needed to identify specialties that have different names but should be considered the same for the purposes of calculating whether a programme is a new starter or not.
TIS21-5720

fix: include curriculum specialtycode

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/AggregateCurriculumMembershipDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapper.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnrichmentIntegrationTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapperTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSpecialtySyncServiceTest.java

The specialty associated with a Programme Membership includes a `blockIndemnity` flag. This flag should be included in the PM data when it is enriched.
Update the AggregateCurriculumMembershDto and associated mapping functions to handle the `blockIndemnity` field. It is a `tinybit` so the raw data in the record will be `1` or `0` when present, and will need converting to a boolean.
TIS21-5617
TIS21-5849

feat: include block indemnity in PM enrichment

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/util/TraineeDetailsUtil.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/PlacementSpecialtyRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSpecialtySyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/SpecialtySyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/SpecialtyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/PlacementEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapperTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/PlacementSpecialtySyncServiceTest.java

Notes:
* Changes to PlacementSpecialty repository: previously we would hold at most one of each PRIMARY and SUB_SPECIALTY type records for any placement, which enabled searching for a unique record by placement and type. Now there can be multiple records for OTHER-type placement specialties. Note that [placementId + specialtyId] is still guaranteed to be unique.
* The otherSpecialties collection contains documents with specialty Id and specialty name. Note that specialty name is not unique within the specialty collection, hence the need to include the id. This could be extended in future if other attributes are of value.
TIS21-5738

feat: include placement other specialties

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/ProgrammeMembershipMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Curriculum.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/CurriculumMembership.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Grade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Person.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Placement.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/PlacementSpecialty.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Post.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/PostSpecialty.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Programme.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/ProgrammeMembership.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Site.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Specialty.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Trust.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/FifoMessagingService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/ProgrammeMembershipMapperTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/CurriculumMembershipTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/CurriculumTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/GradeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/PersonTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/PlacementSpecialtyTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/PlacementTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/PostSpecialtyTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/PostTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/ProgrammeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/SiteTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/SpecialtyTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/model/TrustTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/FifoMessagingServiceTest.java

Otherwise the FifoMessagingService.getMessageGroupId() falls over when entities arrive from the event listeners without these basic attributes set (e.g.:
https://github.com/Health-Education-England/tis-trainee-sync/blob/df14a2ef2ab98c1caa69501a04f6c56393a5c50b/src/main/java/uk/nhs/hee/tis/trainee/sync/event/CurriculumEventListener.java#L65)
TIS21-6040

fix: initialise new Record child classes with table and schema

---

src/main/java/uk/nhs/hee/tis/trainee/sync/service/FifoMessagingService.java

Sorry, another one.
Here's another example of the sort of sequence that just... stops... without the placement queue registering that it has received the object
```
2024-06-06 12:55:01.682 DEBUG 1 --- [nerContainer-16] .t.t.s.e.PlacementSpecialtyEventListener : After placement specialty save, search for placement 1996588 to re-sync
2024-06-06 12:55:01.682 DEBUG 1 --- [nerContainer-16] .t.t.s.e.PlacementSpecialtyEventListener : Placement Record(tisId=1996588, data={placementAddedDate=2021-05-13T16:38:18Z, lifecycleState=APPROVED, gradeId=306, siteCode=A89010, postId=30320, dateFrom=2021-08-04, placementWholeTimeEquivalent=1, traineeId=287923, gradeAbbreviation=ST1, placementType=In Post, dateTo=2022-02-01, siteId=3270, placementAmendedDate=2024-06-06T12:43:47Z, id=1996588, …
```

fix: more logging for fifo queues

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/AggregateProgrammeMembershipDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/TraineeDetailsDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/TraineeDetailsMapper.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

The training pathway is lost due to not being mapped back to the TraineeDetailsDto.
Update the DTO to add the training pathway and update the associated mapper configs to ensure it is populated.
Add a new test to TcsSyncServiceTest to verify that programme membership data is patched as expected.
TIS21-6175
TIS21-6181

fix: carry training pathway to trainee details

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/config/MongoConfiguration.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/LocalOfficeEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/LocalOffice.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/LocalOfficeRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/LocalOfficeSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/config/MongoConfigurationTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/LocalOfficeEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/LocalOfficeSyncServiceTest.java

This is preliminary work for this ticket, just to get the LocalOffice data into the sync db. The actual linking of the DBC --> LocalOffice --> Programme will be done in a follow-up PR based off https://github.com/Health-Education-England/tis-trainee-sync/pull/465
TIS21-6273

feat: include LocalOffice in sync db

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/event/DbcEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/LocalOfficeEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/UserDesignatedBodyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/DbcRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/DbcSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/LocalOfficeSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/DbcEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/LocalOfficeEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/UserDesignatedBodyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/DbcSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/LocalOfficeSyncServiceTest.java

For context see (now removed) comment:
```
//NOTE: refactor this as per: https://hee-tis.atlassian.net/browse/TIS21-6228
//As a Designated body name will no longer be equal to a Local Office name, and the programme
//owner is a Local Office name, the 'findByOwner()' below will become invalid.
//This may require
// (1) sync LocalOffice into sync db as well as reference.
// (2) ensure abbr field is included (its missing from the Reference LocalOffice collection)
// (3) join dbc.abbr <-> LocalOffice.abbreviation and use LocalOffice.name <-> Programme.owner
```
Dependent on
https://github.com/Health-Education-England/TIS-REFERENCE/pull/343 and https://github.com/Health-Education-England/TIS-SYNC/pull/253
TIS21-6273

feat: DBC / LocalOffice Programme owner refactor

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/event/DbcEventListener.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/DbcEventListenerTest.java

To avoid requesting 'related' local offices for DBCs that will never be linked to one.
TIS21-6272

fix: ignore irrelevant DBCs

---

build.gradle.kts
src/main/resources/application-local.yml

For new localstack setup, as per https://github.com/Health-Education-England/tis-trainee-forms/pull/671
I think this will leave the docker-compose env vars as something like:
```
environment:
- DB_HOST=host.docker.internal
- LOCALSTACK_HOST=localstack
- SPRING_PROFILES_ACTIVE=local
- REFERENCE_HOST=tis-trainee-reference
- TRAINEE_DETAILS_HOST=tis-trainee-details
- REDIS_HOST=redis-cache
- REDIS_USER=default
- REDIS_PASSWORD=password
```
which could potentially be slimmed-down a bit further...
NO-TICKET

chore: local app config

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/TisTraineeSyncApplication.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/UserDesignatedBodyEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/event/UserRoleEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacade.java
src/main/java/uk/nhs/hee/tis/trainee/sync/migration/RebuildResponsibleOfficerTables.java
src/main/java/uk/nhs/hee/tis/trainee/sync/repository/UserRoleRepository.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/DbcSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/HeeUserSyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/UserDesignatedBodySyncService.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/UserRoleSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingHeeUserIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingUserDesignatedBodyIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingUserRoleIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/UserDesignatedBodyEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/UserRoleEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/migration/RebuildResponsibleOfficerTablesTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/DbcSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/HeeUserSyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/UserDesignatedBodySyncServiceTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/UserRoleSyncServiceTest.java
src/test/resources/application-int.yml
src/test/resources/application-test.yml

For tables with no ID field, query the database to see if the incoming record is already there and to get a usable ID field for caching purposes. 
Delete:
Use the retrieved ID for the delete, or ignore if the record was not found.
Insert:
For UserRole and UserDesignatedBody, load/insert for existing records is ignored (since there are no additional fields beyond the composite key); for HeeUser the old record is first deleted since other field values might have been updated in the new record.
Mongock to recreate the tables:
These will be populated by redriving the applicable tables in TIS. Existing Responsible Officer entries in trainee profiles are currently correct (afaik), hence the collections can be dropped and recreated instead of deleting all records (which would trigger updates to …

fix: sync RO-related data correctly

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListener.java
src/main/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeMembershipSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/cache/CachingProgrammeMembershipIntTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/event/ProgrammeMembershipEventListenerTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/ProgrammeMembershipSyncServiceTest.java

Currently if a DELETE message is received but no matching PM is found in the sync database the AfterDeleteEvent listener does not fire and downstream services are not notified of the potential deletion.
In most cases this is fine, as the deletion has already occured, but in edge cases where the DELETE message is required again (e.g. cleaning up partial/leftover data from previously failed deletes) the message never makes it to the downstream services leaving them out of date with no way to automatically sync back up.
The original intention of the PM event listener was that it would fire on database events, allowing async handling of updates and deletes de-coupled from the incoming record messages. However, the implementation uses application events instead, which offer no such benefits. …

fix(pm): always delete in downstream services

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapper.java
src/main/java/uk/nhs/hee/tis/trainee/sync/model/Record.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/RecordMapperTest.java

...in notification SNS messages for downstream handling.
With the changes to data requests in tis-sync as per https://github.com/Health-Education-England/TIS-SYNC/pull/257 the expected message arriving in the tis-trainee-sync record queue should include additional metadata fields like
```
{
"data": {
"id": 47165,
"gmcNumber": "7962465",
"gmcStatus": "Registered with License",
"amendedDate": "202-01-01T09:46:00Z"
},
"metadata": {
"timestamp": "2024-12-10T12:01:45.221849Z",
"record-type": "data",
"operation": "update",
"partition-key-type": "schema-table",
"schema-name": "tcs",
"table-name": "GmcDetails",
"transaction-id": 29222969333729,
"tis-trigger": "Update rejected",   <---- new
"tis-trigger-detail": "blah blah blah"  <---- new
}
}
```
the record should be synced as normal, which will …

feat: include TIS trigger metadata

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncService.java
src/test/java/uk/nhs/hee/tis/trainee/sync/service/TcsSyncServiceTest.java

From the AWS docs: "exists matching only works on leaf nodes. It does not work on intermediate nodes." . This means the tisTrigger attribute inside the record is ignored. Our subscription filter is 
```
{
"tisTrigger": [
{
"exists": true
}
]
}
```
Unfortunately the change does nothing to make our message any less verbose. Example:
```
{
"tisId" : "47165",
"tisTrigger" : "Update rejected",
"tisTriggerDetail" : "Received 2025-01-14T09:25:02.125",
"record" : {
"tisId" : "47165",
"data" : {
"id" : "47165",
"gmcNumber" : "UNKNOWN",
"gmcStatus" : "Registered with Licence",
"amendedDate" : "2024-10-10T09:24:08.428"
},
"metadata" : {
"timestamp" : "2025-01-14T09:25:23.178Z",
"record-type" : "data",
"operation" : "load",
"partition-key-type" : "schema-table",
"schema-name" : "tcs",
"table-name" : …
```

fix: tis trigger must be a leaf node for SNS subscription filtering

---

build.gradle.kts
settings.gradle.kts

Use the trainee version catalog to manage dependency version. The following dependencies have been updated automatically by the migration to the catalog.
- Mongock `5.4.2` to `5.4.4`
- Sentry `7.13.0` to `7.20.1`
- Spring Boot (plugin) `3.3.2` to `3.3.8`
- Spring Cloud (BOM) `2023.0.3` to `2023.0.5`
- Spring Dependency Management (plugin) `1.1.6` to `1.1.7`
NO-TICKET

chore: migrate to trainee version catalog

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/dto/AggregateProgrammeMembershipDto.java
src/main/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapper.java
src/test/java/uk/nhs/hee/tis/trainee/sync/facade/ProgrammeMembershipEnricherFacadeTest.java
src/test/java/uk/nhs/hee/tis/trainee/sync/mapper/AggregateMapperTest.java

The admin endpoints for LTFT forms require filtering based on the admin's local office, which can be determined using the `cognito:groups` from the auth token.
The group name is the DBC, rather than a name, so to avoid having to hardcode a mapping the code should be added to the PM so it can be referenced in the LTFT data.
TIS21-6599
TIS21-6938

feat: include DBC in programme membership

---

build.gradle.kts
src/main/java/uk/nhs/hee/tis/trainee/sync/TisTraineeSyncApplication.java
src/test/java/uk/nhs/hee/tis/trainee/sync/config/ApplicationConfigurationTest.java

The MessageConverter no longer needs to be manually created to include the ObjectMapper, as the SQS starter now handles it automatically. The current MessageConverter is now conflicting with the auto-configuration so should be removed.
Move the RestTemplate config from the main application class to the ApplicationConfiguration class.
NO-TICKET

refactor: message convert configuration
